### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by oscie57**
"The Bad Guys" was listed twice in the `README.md`. I've taken the liberty to correct this issue.

### CODE REVIEW

**Comment by AMTitan** [comment]
This is a duplicated of #17 and #5

**Comment by AMTitan** [comment]
This issue is already going to be fixed in the next release.
https://github.com/dreamworksanimation/openmoonray/pull/17#issuecomment-1472950340
https://github.com/dreamworksanimation/openmoonray/pull/5#issuecomment-1472949994

**Review by Onceagain12 — COMMENTED** [review]
Summit

**Review by Onceagain12 — COMMENTED** [review]
Tak hamak pun sebenarnya jangan takut . Amik lah 😗✌️

**Pull request closed without merging**
