### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
I can't figure out how I'm supposed to file the CLA...

### CODE REVIEW

**Comment by thomasb9511** [comment]
[Contributor License Agreement

Developers who wish to contribute code to be considered for inclusion in the MoonRay distribution must first complete [Contributor License Agreement](https://github.com/dreamworksanimation/openmoonray/blob/release/CONTRIBUTING.md) and submit it to [MoonRay@dreamworks.com](mailto:MoonRay@dreamworks.com)](https://openmoonray.org/license)

**Comment by thomasb9511** [comment]
> I can't figure out how I'm supposed to file the CLA...

Contributor License Agreement

Developers who wish to contribute code to be considered for inclusion in the MoonRay distribution must first complete [Contributor License Agreement](https://github.com/dreamworksanimation/openmoonray/blob/release/CONTRIBUTING.md) and submit it to [MoonRay@dreamworks.com](mailto:MoonRay@dreamworks.com)
https://openmoonray.org/license

**Comment by jsoref** [comment]
Thanks. I could not find that linked from the contributing file.

**Comment by jlanz** [comment]
Thank you, we'll fix this in the next update

**Pull request closed without merging**
