### PR TITLE
MoonRay build on Rocky Linux 9 using Apptainer (formerly Singularity)

### PR DESCRIPTION
**Pull request by panda1100**
Apptainer definition files for building MoonRay on Rocky Linux 9
Build procedures for building MoonRay using Apptainer
Signed-off-by: Yoshiaki Senda <yoshiaki@live.it>

### CODE REVIEW

**Comment by panda1100** [comment]
I submitted Individual CLA.

**Comment by PaulCharlton** [comment]
1. your changes are in the `building` folder, which is also used for Docker builds. as such,
2. the Docker builds will include all of your files since they are not excluded with a `.dockerignore`.
3. ideally, docker and apptainer would build from separate folders.  perhaps `building/apptainer` and `building/docker` for distinction
4. idiomatically, the apptainer submissions includes a lot of embedded shell code —
5. ideally, the shell code would be in separate `.sh` files so that an off-the-shelf linter can inspect them
6. regarding exported variables — seems like you want them exported and used BEFORE the start of the user process in apptainer, rather than “post_launch”

**Comment by panda1100** [comment]
@PaulCharlton I have updated this PR. Could you please check updates?

**Comment by NicTanghe** [comment]
step 2 is unclear for me 

```
  ## Step 2. Build the remaining dependencies
  --------


  installed using CMake. CMakeLists.txt in the building directory contains a series of
  Apart from Optix, the remaining MoonRay dependencies can be built from source and
  targets that download the sources and build each dependency.

    > apptainer build --bind ~/openmoonray:/source/openmoonray moonray-rocky9-depbuild.sif

  moonray-rocky9-depbuild.def
 
```

It is unclear to me what is being bound to what.

if i have the repo locally at

~/git/source/openmoonray

Do i need to use ? maybe a little note whould be handy instead of asuming an instal in the root of home ?


pptainer build --bind ~/git/source/openmoonray:/source/openmoonray moonray-rocky9-depbuild.sif

**Comment by panda1100** [comment]
Thank you @NicTanghe for your feedback! I will answer your one by one and then I will update document.

1. Bind mount

When you pulled openmoonray on  `~/git/source/openmoonray`, build command looks like the following:

```
apptainer build --bind ~/git/source/openmoonray:/source/openmoonray moonray-rocky9-depbuild.sif moonray-rocky9-depbuild.def 
```

apptainer `--bind` mount option takes `<Directory_on_Host>`:`<Directory_inside_Container>` as argument. This way we only pull repository once and easy to customize your build because you can edit files under `~/git/source/openmoonray` from host machine.

**Comment by panda1100** [comment]
@NicTanghe

>  2 lines are in reverse ?
No, those are not reverse. When you pulled openmoonray on `~/git/source/openmoonray`:

```
cd ~/git/source/openmoonray/building/apptainer
apptainer build moonray-rocky9-base.sif moonray-rocky9-base.def
```

Because container definition files are located under `~/git/source/openmoonray/building/apptainer` directory.

> WARNING: integrity: signature not found for object group 1
> WARNING: Bootstrap image could not be verified, but build will continue.

and warning messages you got is ignorable. Using Apptainer we can cryptographically signed our container to prove who built the container. This time I skipped signing part when we built base container, so that Apptainer emit those warnings when you build dependencies build and MoonRay build. That basically means "You are using unsigned container for your build, please be aware of that".

**Comment by NicTanghe** [comment]
Hello thx for your quick reply !
and information.
That is what i ended up doing (unless i made a typo)
but i get stuck testing. the ggui

```bash
✦ ❯ apptainer shell moonray-rocky9.sif
    MoonRay> moonray -in ~/openmoonray/testdata/rectangle.rdla -out /tmp/rectangle.exr
Setting up release in /installs/openmoonray
Building shader descriptions...
...done
MoonRay> exit

✦ ❯ apptainer shell moonray-rocky9.sif
Setting up release in /installs/openmoonray
MoonRay> moonray_gui -in ~/openmoonray/testdata/rectangle.rdla -out /tmp/rectangle.exr
QStandardPaths: error creating runtime directory '/run/user/1000' (Function not implemented)
No path input. Snapshot path set to current directory.
Welcome to Moonray GUI. Press H while running the application to open the hotkey guide.
ERROR: Failed to add file watcher for '/home/nanghe/openmoonray/testdata/rectangle.rdla': No such file or directory
MoonRay>

**Comment by panda1100** [comment]
@NicTanghe 

```
MoonRay>  moonray_gui -in ~/git/source/openmoonray/testdata/rectangle.rdla -out /tmp/rectangle.exr
```

This should work on your environment.

**Comment by NicTanghe** [comment]
yes i had already realise d the path ws local again.,

i`m a bit confused now how to get the build out of the container into my local system. 
thx so much for helping me and making this !

**Comment by panda1100** [comment]
@NicTanghe There are differences between Docker and Apptainer (formerly Singularity). Apptainer is originally designed for HPC (High Performance Computing). Apptainer automatically mount your home directory and other necessary path.
https://apptainer.org/docs/user/main/bind_paths_and_mounts.html#system-defined-bind-paths

I'm glad that works for you. I will definitely update document to reflect your feedback!

**Comment by panda1100** [comment]
@NicTanghe Maybe I should write "simple" version and "detailed" version of build procedures to prevent confusion. What do you think about this approach? Simple version will look like the following:

Simple version of Step1 to Step3 (I intentionally used my fork uri here because this PR not merged yet.). `moonray.sh` do everything for you.

```
git clone --recurse-submodules https://github.com/panda1100/openmoonray.git
export WORKDIR=$(pwd)
./openmoonray/building/apptainer/moonray.sh
```

and then jump to Step 4

```
apptainer shell --nv moonray-rocky9.sif
MoonRay> moonray_gui -in /openmoonray/testdata/rectangle.rdla -out /tmp/rectangle.exr
```
and add example how to use **your data** that located under your home directory (or somewhere outside of container).


Detail version will explain each steps and Apptainer basics, for example "bind mount", "how to utilize GPU etc".

**Comment by panda1100** [comment]
I have updated test procedures, please see discussion page https://github.com/dreamworksanimation/openmoonray/discussions/68#discussioncomment-5405118

**Comment by panda1100** [comment]
add minicord dependencies
related discussion: https://github.com/dreamworksanimation/openmoonray/discussions/94

**Comment by panda1100** [comment]
add `minicoord.def` separate minicoord container definition file

**Comment by panda1100** [comment]
Thank you @rgwilson68 -san for letting me know about upcoming changes :)
That's great to hear that Moonray project support Rocky Linux 9 🎉 
I'll revisit Apptainer definition files after that exciting updates!

**Comment by panda1100** [comment]
@rgwilson68 Rob-san,
Please ping me anytime when you need helping hands on porting OpenMoonRay to Rocky9.

**Comment by panda1100** [comment]
@rgwilson68 I just found the regression. The following change "libcgroup (cgroup v1) mark as dead" on upstream break the MoonRay build on EL9. I'm looking for the solution now. Do you have any plan updating cgroup v1 dependency to cgroup v2? 

https://issues.redhat.com/browse/CS-546?atlOrigin=eyJpIjoiY2QyZTJiZDRkNGZhNGZlMWI3NzRkNTBmZmVlNzNiZTkiLCJwIjoianN3LWdpdGxhYi1pbnQifQ

**Comment by panda1100** [comment]
I'm working on this again to catch up v1.3.0.0. libcgroup packages are not available even on kojihub.stream.centos.org, I'll check what component actually depends on libcgroup (cgroup v1).

**Comment by panda1100** [comment]
I made new PR #122. Close this PR.

**Pull request closed without merging**
